apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

# setting image tag for qa:
images:
- name: my-app-image-qa
  newName:  ghcr.io/memor24/kuber-kustomize-gitops/my-app-image/
  newTag: v1.1.$c # v1.qa.counter