apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

# setting image tag for dev:
images:
- name: my-app-image-dev
  newName:  ghcr.io/memor24/kk-image
  newTag: v1.0.${BUILD_NUMBER} # v1.dev.counter

patchesStrategicMerge:
 - patch-deployment.yml
 - patch-service.yml