apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

# setting image tag for prod:
images:
- name: my-app-image-prod
  newName:  ghcr.io/memor24/kuber-kustomize-gitops/my-app-image/
  newTag: v1.2.${BUILD_NUMBER} # v1.staging.counter