apiVersion: v1 
kind: Service
metadata:
  name: my-app-service
  annotations:
     environment: "prod"
     monitoring: "enabled"
spec:
  type: ClusterIP
  ports:
    - name: http-proxy
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-app
    environment: prod